In [51]:
import numpy as np
import pandas as pd
import math

data = np.loadtxt("/Users/guilhermegarcia/GLCGarcia documents /University /3rd year 2023 /Summer Development Internship /Tc-python/Fe3H8.txt")

#data = pd.read_csv("/Users/guilhermegarcia/GLCGarcia documents /University /3rd year 2023 /Summer Development Internship /Tc-python/Fe3H8.txt" , sep = " ", header = None)

print(data[2])

mu = 0.10

print(len(data))

for i in range (0,len(data)):

    #Tc using macmillan formula

    Tc = ((data[i][3]) / 1.2) * math.e ** ((-1.04 * (1 + data[i][1]))/(data[i][1] * (1 - 0.62 * mu) - mu))
    
    print(Tc)

    #print("For Broadening " + data[2][0] + "Tc is" + Tc)

[6.000000e-02 1.074000e+00 4.039500e+00 6.482994e+02]
10
51.66356689274893
50.57191900272474
50.14832637501418
46.2253393678985
44.09134806540263
43.44933791047361
43.354291532306725
43.36216348787757
43.31928223263432
43.24505529607407


In [59]:
data = np.loadtxt("/Users/guilhermegarcia/GLCGarcia documents /University /3rd year 2023 /Summer Development Internship /Tc-python/FeH-new.dat")

#data = pd.read_csv("/Users/guilhermegarcia/GLCGarcia documents /University /3rd year 2023 /Summer Development Internship /Tc-python/Fe3H8.txt" , sep = " ", header = None)

print(data[2])

mu = 0.13

# print(len(data))

for i in range (0,len(data)):

    #Tc using macmillan formula

    Tc = ((data[i][3]) / 1.2) * math.e ** ((-1.04 * (1 + data[i][1]))/(data[i][1] * (1 - 0.62 * mu) - mu))
    
    print(Tc)


[6.0000000e-02 3.0360000e-01 8.4821000e+00 2.9748001e+03]
10
5.1897764775803505
0.38951545030100554
0.27931350766260443
0.1824608783656148
0.08240629717143862
0.028835298619300804
0.008431868188616923
0.002212647662635769
0.0005342591952085631
0.00012126367553691621


In [65]:
data = np.loadtxt("/Users/guilhermegarcia/GLCGarcia documents /University /3rd year 2023 /Summer Development Internship /Tc-python/FeH3-new.dat")

#data = pd.read_csv("/Users/guilhermegarcia/GLCGarcia documents /University /3rd year 2023 /Summer Development Internship /Tc-python/Fe3H8.txt" , sep = " ", header = None)

print(data[2])

mu = 0.15

print(len(data))

for i in range (0,len(data)):

    #Tc using macmillan formula

    Tc = ((data[i][3]) / 1.2) * math.e ** ((-1.04 * (1 + data[i][1]))/(data[i][1] * (1 - 0.62 * mu) - mu))
    
    print(Tc)

[6.000000e-02 3.105400e+00 2.141300e+00 5.247296e+02]
10
124.91921007169307
104.06842688937388
88.18299781258769
74.71316217994517
61.910269981111625
50.48848004637467
41.87423332163826
36.71361679669512
34.53641551710802
34.366741220890624
